import { Category, Flashcard } from './types';

export const categories: Category[] = [
  { id: 'temel', title: 'Temel İfadeler', description: 'Günlük hayatta en sık kullanılan kelimeler', iconName: 'MessageCircle' },
  { id: 'sayilar', title: 'Sayılar', description: "0'dan 1000'e kadar temel sayılar", iconName: 'Hash' },
  { id: 'renkler', title: 'Renkler', description: 'Ana ve ara renkler', iconName: 'Palette' },
  { id: 'sorular', title: 'Soru Kalıpları', description: 'Kim, Ne, Nerede gibi temel sorular', iconName: 'HelpCircle' },
  { id: 'yonler', title: 'Yön Bulma', description: 'Adres sorma ve yön tarifleri', iconName: 'MapPin' },
  { id: 'tanisma', title: 'Kendini Tanıtma', description: 'İsim, yaş, meslek ve nereli olduğunu söyleme', iconName: 'User' },
  { id: 'alisveris', title: 'Alışveriş', description: 'Fiyat sorma ve mağaza diyalogları', iconName: 'ShoppingCart' },
];

export const flashcards: Flashcard[] = [
  // TEMEL İFADELER
  { id: 't1', categoryId: 'temel', greek: 'Γεια σου', pronunciation: 'Ya su', turkish: 'Merhaba (Tekil/Samimi)' },
  { id: 't2', categoryId: 'temel', greek: 'Γεια σας', pronunciation: 'Ya sas', turkish: 'Merhaba (Çoğul/Resmi)' },
  { id: 't3', categoryId: 'temel', greek: 'Καλημέρα', pronunciation: 'Kalimera', turkish: 'Günaydın' },
  { id: 't4', categoryId: 'temel', greek: 'Καλησπέρα', pronunciation: 'Kalispera', turkish: 'İyi akşamlar' },
  { id: 't5', categoryId: 'temel', greek: 'Καληνύχτα', pronunciation: 'Kalinihta', turkish: 'İyi geceler' },
  { id: 't6', categoryId: 'temel', greek: 'Αντίο', pronunciation: 'Andio', turkish: 'Hoşça kal' },
  { id: 't7', categoryId: 'temel', greek: 'Παρακαλώ', pronunciation: 'Parakalo', turkish: 'Lütfen / Bir şey değil' },
  { id: 't8', categoryId: 'temel', greek: 'Ευχαριστώ', pronunciation: 'Efharisto', turkish: 'Teşekkür ederim' },
  { id: 't9', categoryId: 'temel', greek: 'Ναι', pronunciation: 'Ne', turkish: 'Evet' },
  { id: 't10', categoryId: 'temel', greek: 'Όχι', pronunciation: 'Ohi', turkish: 'Hayır' },
  { id: 't11', categoryId: 'temel', greek: 'Συγγνώμη', pronunciation: 'Signomi', turkish: 'Özür dilerim / Afedersiniz' },
  { id: 't12', categoryId: 'temel', greek: 'Εντάξει', pronunciation: 'Endaksi', turkish: 'Tamam' },
  { id: 't13', categoryId: 'temel', greek: 'Ίσως', pronunciation: 'Isos', turkish: 'Belki' },
  { id: 't14', categoryId: 'temel', greek: 'Δεν καταλαβαίνω', pronunciation: 'Den katalaveno', turkish: 'Anlamıyorum' },
  { id: 't15', categoryId: 'temel', greek: 'Μιλάτε αγγλικά;', pronunciation: 'Milate anglika?', turkish: 'İngilizce konuşur musunuz?' },
  { id: 't16', categoryId: 'temel', greek: 'Πώς είσαι;', pronunciation: 'Pos ise?', turkish: 'Nasılsın?' },
  { id: 't17', categoryId: 'temel', greek: 'Πολύ καλά', pronunciation: 'Poli kala', turkish: 'Çok iyi' },
  { id: 't18', categoryId: 'temel', greek: 'Έτσι κι έτσι', pronunciation: 'Etsi ki etsi', turkish: 'Şöyle böyle' },
  { id: 't19', categoryId: 'temel', greek: 'Τι κάνεις;', pronunciation: 'Ti kanis?', turkish: 'Ne yapıyorsun? / Nasılsın?' },
  { id: 't20', categoryId: 'temel', greek: 'Ορίστε', pronunciation: 'Oriste', turkish: 'Buyurun / Efendim' },

  // SAYILAR
  { id: 's0', categoryId: 'sayilar', greek: 'Μηδέν', pronunciation: 'Miden', turkish: 'Sıfır' },
  { id: 's1', categoryId: 'sayilar', greek: 'Ένα / Μία', pronunciation: 'Ena / Mia', turkish: 'Bir' },
  { id: 's2', categoryId: 'sayilar', greek: 'Δύο', pronunciation: 'Dio', turkish: 'İki' },
  { id: 's3', categoryId: 'sayilar', greek: 'Τρία', pronunciation: 'Tria', turkish: 'Üç' },
  { id: 's4', categoryId: 'sayilar', greek: 'Τέσσερα', pronunciation: 'Tesera', turkish: 'Dört' },
  { id: 's5', categoryId: 'sayilar', greek: 'Πέντε', pronunciation: 'Pende', turkish: 'Beş' },
  { id: 's6', categoryId: 'sayilar', greek: 'Έξι', pronunciation: 'Eksi', turkish: 'Altı' },
  { id: 's7', categoryId: 'sayilar', greek: 'Επτά', pronunciation: 'Epta', turkish: 'Yedi' },
  { id: 's8', categoryId: 'sayilar', greek: 'Οκτώ', pronunciation: 'Okto', turkish: 'Sekiz' },
  { id: 's9', categoryId: 'sayilar', greek: 'Εννέα', pronunciation: 'Enea', turkish: 'Dokuz' },
  { id: 's10', categoryId: 'sayilar', greek: 'Δέκα', pronunciation: 'Deka', turkish: 'On' },
  { id: 's11', categoryId: 'sayilar', greek: 'Έντεκα', pronunciation: 'Endeka', turkish: 'On bir' },
  { id: 's12', categoryId: 'sayilar', greek: 'Δώδεκα', pronunciation: 'Dodeka', turkish: 'On iki' },
  { id: 's20', categoryId: 'sayilar', greek: 'Είκοσι', pronunciation: 'Ikosi', turkish: 'Yirmi' },
  { id: 's30', categoryId: 'sayilar', greek: 'Τριάντα', pronunciation: 'Trianda', turkish: 'Otuz' },
  { id: 's40', categoryId: 'sayilar', greek: 'Σαράντα', pronunciation: 'Saranda', turkish: 'Kırk' },
  { id: 's50', categoryId: 'sayilar', greek: 'Πενήντα', pronunciation: 'Peninda', turkish: 'Elli' },
  { id: 's60', categoryId: 'sayilar', greek: 'Εξήντα', pronunciation: 'Exinda', turkish: 'Altmış' },
  { id: 's70', categoryId: 'sayilar', greek: 'Εβδομήντα', pronunciation: 'Evdominda', turkish: 'Yetmiş' },
  { id: 's80', categoryId: 'sayilar', greek: 'Ογδόντα', pronunciation: 'Ogdonda', turkish: 'Seksen' },
  { id: 's90', categoryId: 'sayilar', greek: 'Ενενήντα', pronunciation: 'Eneninda', turkish: 'Doksan' },
  { id: 's100', categoryId: 'sayilar', greek: 'Εκατό', pronunciation: 'Ekato', turkish: 'Yüz' },
  { id: 's1000', categoryId: 'sayilar', greek: 'Χίλια', pronunciation: 'Hilia', turkish: 'Bin' },

  // RENKLER
  { id: 'r1', categoryId: 'renkler', greek: 'Κόκκινο', pronunciation: 'Kokino', turkish: 'Kırmızı' },
  { id: 'r2', categoryId: 'renkler', greek: 'Μπλε', pronunciation: 'Ble', turkish: 'Mavi' },
  { id: 'r3', categoryId: 'renkler', greek: 'Πράσινο', pronunciation: 'Prasino', turkish: 'Yeşil' },
  { id: 'r4', categoryId: 'renkler', greek: 'Κίτρινο', pronunciation: 'Kitrino', turkish: 'Sarı' },
  { id: 'r5', categoryId: 'renkler', greek: 'Μαύρο', pronunciation: 'Mavro', turkish: 'Siyah' },
  { id: 'r6', categoryId: 'renkler', greek: 'Άσπρο / Λευκό', pronunciation: 'Aspro / Lefko', turkish: 'Beyaz' },
  { id: 'r7', categoryId: 'renkler', greek: 'Γκρι', pronunciation: 'Gri', turkish: 'Gri' },
  { id: 'r8', categoryId: 'renkler', greek: 'Πορτοκαλί', pronunciation: 'Portokali', turkish: 'Turuncu' },
  { id: 'r9', categoryId: 'renkler', greek: 'Ροζ', pronunciation: 'Roz', turkish: 'Pembe' },
  { id: 'r10', categoryId: 'renkler', greek: 'Καφέ', pronunciation: 'Kafe', turkish: 'Kahverengi' },
  { id: 'r11', categoryId: 'renkler', greek: 'Μωβ', pronunciation: 'Mov', turkish: 'Mor' },
  { id: 'r12', categoryId: 'renkler', greek: 'Γαλάζιο', pronunciation: 'Galazio', turkish: 'Açık Mavi' },
  { id: 'r13', categoryId: 'renkler', greek: 'Χρυσό', pronunciation: 'Hriso', turkish: 'Altın' },
  { id: 'r14', categoryId: 'renkler', greek: 'Ασημί', pronunciation: 'Asimi', turkish: 'Gümüş' },

  // SORU KALIPLARI
  { id: 'q1', categoryId: 'sorular', greek: 'Τι;', pronunciation: 'Ti?', turkish: 'Ne?' },
  { id: 'q2', categoryId: 'sorular', greek: 'Πού;', pronunciation: 'Pu?', turkish: 'Nerede?' },
  { id: 'q3', categoryId: 'sorular', greek: 'Πότε;', pronunciation: 'Pote?', turkish: 'Ne zaman?' },
  { id: 'q4', categoryId: 'sorular', greek: 'Γιατί;', pronunciation: 'Yati?', turkish: 'Neden?' },
  { id: 'q5', categoryId: 'sorular', greek: 'Ποιος;', pronunciation: 'Pios?', turkish: 'Kim?' },
  { id: 'q6', categoryId: 'sorular', greek: 'Πώς;', pronunciation: 'Pos?', turkish: 'Nasıl?' },
  { id: 'q7', categoryId: 'sorular', greek: 'Πόσο;', pronunciation: 'Poso?', turkish: 'Ne kadar?' },
  { id: 'q8', categoryId: 'sorular', greek: 'Ποιο;', pronunciation: 'Pio?', turkish: 'Hangisi?' },
  { id: 'q9', categoryId: 'sorular', greek: 'Πού είναι...', pronunciation: 'Pu ine...', turkish: '... nerede?' },
  { id: 'q10', categoryId: 'sorular', greek: 'Μπορείτε να με βοηθήσετε;', pronunciation: 'Borite na me voithisete?', turkish: 'Bana yardım edebilir misiniz?' },
  { id: 'q11', categoryId: 'sorular', greek: 'Καταλαβαίνετε;', pronunciation: 'Katalavenete?', turkish: 'Anlıyor musunuz?' },
  { id: 'q12', categoryId: 'sorular', greek: 'Τι είναι αυτό;', pronunciation: 'Ti ine afto?', turkish: 'Bu nedir?' },
  { id: 'q13', categoryId: 'sorular', greek: 'Μπορείτε να το επαναλάβετε;', pronunciation: 'Borite na to epanalavete?', turkish: 'Bunu tekrar edebilir misiniz?' },
  { id: 'q14', categoryId: 'sorular', greek: 'Από πού είσαι;', pronunciation: 'Apo pu ise?', turkish: 'Nerelisin?' },

  // YÖN BULMA
  { id: 'd1', categoryId: 'yonler', greek: 'Δεξιά', pronunciation: 'Deksia', turkish: 'Sağ' },
  { id: 'd2', categoryId: 'yonler', greek: 'Αριστερά', pronunciation: 'Aristera', turkish: 'Sol' },
  { id: 'd3', categoryId: 'yonler', greek: 'Ευθεία', pronunciation: 'Efthia', turkish: 'Düz' },
  { id: 'd4', categoryId: 'yonler', greek: 'Πίσω', pronunciation: 'Piso', turkish: 'Geri' },
  { id: 'd5', categoryId: 'yonler', greek: 'Μπροστά', pronunciation: 'Brosta', turkish: 'İleri / Ön' },
  { id: 'd6', categoryId: 'yonler', greek: 'Βόρεια', pronunciation: 'Voria', turkish: 'Kuzey' },
  { id: 'd7', categoryId: 'yonler', greek: 'Νότια', pronunciation: 'Notia', turkish: 'Güney' },
  { id: 'd8', categoryId: 'yonler', greek: 'Ανατολικά', pronunciation: 'Anatolika', turkish: 'Doğu' },
  { id: 'd9', categoryId: 'yonler', greek: 'Δυτικά', pronunciation: 'Ditika', turkish: 'Batı' },
  { id: 'd10', categoryId: 'yonler', greek: 'Εδώ', pronunciation: 'Edo', turkish: 'Burada' },
  { id: 'd11', categoryId: 'yonler', greek: 'Εκεί', pronunciation: 'Eki', turkish: 'Şurada / Orada' },
  { id: 'd12', categoryId: 'yonler', greek: 'Μακριά', pronunciation: 'Makria', turkish: 'Uzak' },
  { id: 'd13', categoryId: 'yonler', greek: 'Κοντά', pronunciation: 'Konda', turkish: 'Yakın' },
  { id: 'd14', categoryId: 'yonler', greek: 'Στη γωνία', pronunciation: 'Sti gonia', turkish: 'Köşede' },
  { id: 'd15', categoryId: 'yonler', greek: 'Απέναντι', pronunciation: 'Apenandi', turkish: 'Karşıda / Karşısında' },
  { id: 'd16', categoryId: 'yonler', greek: 'Ο σταθμός', pronunciation: 'O stathmos', turkish: 'İstasyon' },
  { id: 'd17', categoryId: 'yonler', greek: 'Το αεροδρόμιο', pronunciation: 'To aerodromio', turkish: 'Havalimanı' },
  { id: 'd18', categoryId: 'yonler', greek: 'Ο δρόμος', pronunciation: 'O dromos', turkish: 'Sokak / Yol' },

  // KENDİNİ TANITMA
  { id: 'i1', categoryId: 'tanisma', greek: 'Με λένε...', pronunciation: 'Me lene...', turkish: 'Benim adım...' },
  { id: 'i2', categoryId: 'tanisma', greek: 'Χαίρω πολύ', pronunciation: 'Hero poli', turkish: 'Tanıştığıμα memnun oldum' },
  { id: 'i3', categoryId: 'tanisma', greek: 'Είμαι από την Τουρκία', pronunciation: 'Ime apo tin Turkia', turkish: 'Türkiyeliyim' },
  { id: 'i4', categoryId: 'tanisma', greek: 'Πόσων χρονών είσαι;', pronunciation: 'Poson hronon ise?', turkish: 'Kaç yaşındasın?' },
  { id: 'i5', categoryId: 'tanisma', greek: 'Είμαι... χρονών', pronunciation: 'Ime... hronon', turkish: 'Ben ... yaşındayım' },
  { id: 'i6', categoryId: 'tanisma', greek: 'Τι δουλειά κάνεις;', pronunciation: 'Ti dulia kanis?', turkish: 'Ne iş yapıyorsun?' },
  { id: 'i7', categoryId: 'tanisma', greek: 'Είμαι φοιτητής', pronunciation: 'Ime fititis', turkish: 'Ben (erkek) öğrenciyim' },
  { id: 'i8', categoryId: 'tanisma', greek: 'Είμαι φοιτήτρια', pronunciation: 'Ime fititria', turkish: 'Ben (kadın) öğrenciyim' },
  { id: 'i9', categoryId: 'tanisma', greek: 'Πού μένεις;', pronunciation: 'Pu menis?', turkish: 'Nerede yaşıyorsun?' },
  { id: 'i10', categoryId: 'tanisma', greek: 'Μένω στην Αθήνα', pronunciation: 'Meno stin Athina', turkish: "Atina'da yaşıyorum" },

  // ALIŞVERİŞ
  { id: 'a1', categoryId: 'alisveris', greek: 'Πόσο κοστίζει;', pronunciation: 'Poso kostizi?', turkish: 'Ne kadar tutuyor / Fiyatı ne?' },
  { id: 'a2', categoryId: 'alisveris', greek: 'Πόσο κάνει;', pronunciation: 'Poso kani?', turkish: 'Ne kadar (eder)?' },
  { id: 'a3', categoryId: 'alisveris', greek: 'Είναι πολύ ακριβό', pronunciation: 'Ine poli akrivo', turkish: 'Çok pahalı' },
  { id: 'a4', categoryId: 'alisveris', greek: 'Είναι φθηνό', pronunciation: 'Ine fthino', turkish: 'Ucuz' },
  { id: 'a5', categoryId: 'alisveris', greek: 'Έχετε έκπτωση;', pronunciation: 'Ehete ekptosi?', turkish: 'İndiriminiz var mı?' },
  { id: 'a6', categoryId: 'alisveris', greek: 'Δέχεστε πιστωτικές κάρτες;', pronunciation: 'Deheste pistotikes kartes?', turkish: 'Kredi kartı kabul ediyor musunuz?' },
  { id: 'a7', categoryId: 'alisveris', greek: 'Μόνο μετρητά', pronunciation: 'Mono metrita', turkish: 'Sadece nakit' },
  { id: 'a8', categoryId: 'alisveris', greek: 'Μπορώ να έχω απόδειξη;', pronunciation: 'Boro na eho apodiksi?', turkish: 'Fiş alabilir miyim?' },
  { id: 'a9', categoryId: 'alisveris', greek: 'Θα το πάρω', pronunciation: 'Tha to paro', turkish: 'Bunu alacağım' },
  { id: 'a10', categoryId: 'alisveris', greek: 'Απλά κοιτάζω', pronunciation: 'Apla kitazo', turkish: 'Sadece bakıyorum' },
  { id: 'a11', categoryId: 'alisveris', greek: 'Είναι ανοιχτά;', pronunciation: 'Ine anihta?', turkish: 'Açık mı?' },
  { id: 'a12', categoryId: 'alisveris', greek: 'Είναι κλειστά', pronunciation: 'Ine klista', turkish: 'Kapalı' },
  { id: 'a13', categoryId: 'alisveris', greek: 'Τι νούμερο;', pronunciation: 'Ti numero?', turkish: 'Hangi beden / numara?' },
  { id: 'a14', categoryId: 'alisveris', greek: 'Έχετε άλλο χρώμα;', pronunciation: 'Ehete alo hroma?', turkish: 'Başka rengi var mı?' },
  { id: 'a15', categoryId: 'alisveris', greek: 'Το ταμείο', pronunciation: 'To tamio', turkish: 'Kasa' },
];
